{{- range $app := .Values.Applications -}}
{{- if .enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ default "argocd" $.Values.global.argocdNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
spec:
  project: {{ default "default" .project }}
  {{- if .sources }}
  sources:
    {{- toYaml .sources | nindent 4 }}
  {{- end }}
  destination:
    namespace: {{ default "default" .namespace }}
    server: {{ default "https://kubernetes.default.svc" .server }}
  syncPolicy:
    {{- if .syncPolicy }}
    {{- toYaml .syncPolicy | nindent 4 }}
    {{- else }}
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    {{- end }}
---
{{- end }}
{{- end }}
