{{- range $project := .Values.Projects -}}
{{- if .enable }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ default "argocd" $.Values.global.argocdNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave }}"
  labels:
    app.kubernetes.io/part-of: {{ default $.Values.global.partOf .name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .description }}
  {{- if .labels }}
  metadata:
    labels:
      {{- toYaml .labels | nindent 6 }}
  {{- end }}
  {{- if .clusterResourceWhitelist }}
  clusterResourceWhitelist:
    {{- toYaml .clusterResourceWhitelist | nindent 4 }}
  {{- end }}
  {{- if .destinations }}
  destinations:
    {{- toYaml .destinations | nindent 4 }}
  {{- end }}
  {{- if .sourceRepos }}
  sourceRepos:
    {{- toYaml .sourceRepos | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
