global:
  argocdNamespace: argocd
  repoURL: git@github.com:adiii717/k8s-gitops.git
  targetRevision: main
  partOf: root-manifest

# ArgoCD Manifest Project - manages all other projects
Projects:
  argocd-manifest:
    enable: true
    syncWave: -1
    name: argocd-manifest
    description: Root project for managing all GitOps projects
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    destinations:
      - namespace: '*'
        server: https://kubernetes.default.svc
    sourceRepos:
      - '*'

# Top-level Applications that manage projects
# Each application points to a project's root.yaml
Applications:
  devops:
    enable: true
    syncWave: 100
    name: devops
    description: DevOps tools and services
    namespace: argocd
    project: argocd-manifest
    sources:
      - repoURL: git@github.com:adiii717/k8s-gitops.git
        targetRevision: main
        ref: values
      - repoURL: git@github.com:adiii717/k8s-gitops.git
        targetRevision: main
        path: argocd-manifest
        helm:
          releaseName: devops
          valueFiles:
            - $values/projects/devops/root.yaml

  frontend:
    enable: false
    syncWave: 101
    name: frontend
    description: Frontend applications
    namespace: argocd
    project: argocd-manifest
    sources:
      - repoURL: git@github.com:adiii717/k8s-gitops.git
        targetRevision: main
        ref: values
      - repoURL: git@github.com:adiii717/k8s-gitops.git
        targetRevision: main
        path: argocd-manifest
        helm:
          releaseName: frontend
          valueFiles:
            - $values/projects/frontend/root.yaml
